export const SET_MENU_TOGGLE = 'SET_MENU_TOGGLE'

export const DISPATCH_SEARCH_MOV = 'DISPATCH_SEARCH_MOV'
export const DISPATCH_TODAY_BOX_OFFICE = 'DISPATCH_TODAY_BOX_OFFICE'
export const SET_MOVIES = 'SET_MOVIES'
export const SET_BOX_OFFICE = 'SET_BOX_OFFICE'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const SET_BOX_OFFICE_SETTING_POPUP = 'SET_BOX_OFFICE_SETTING_POPUP'
export const SET_NATION_CODE = 'SET_NATION_CODE'
